name: Node.js

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: "true"

    services:
      postgres:
        image: postgres:12
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: turret_dev
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: turret_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 2s
          --health-retries 2

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.0"

      - name: Cache npm dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn

      - name: Configure dotenv
        run: cp .env.dist .env

      - name: Migrate the database
        run: node scripts/syncDatabase.js

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Test End-to-end
        run: yarn test:e2e
