name: Node.js

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: "true"

    services:
      postgres:
        image: postgres:12
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: turret_dev
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: turret_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 2s
          --health-retries 2

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.0"

      - name: Setup local HTTPS
        run: |
          sudo apt install libnss3-tools
          wget https://github.com/FiloSottile/mkcert/releases/download/v1.1.2/mkcert-v1.1.2-linux-amd64
          mv mkcert-v1.1.2-linux-amd64 mkcert
          chmod +x mkcert
          ./mkcert -install
          ./mkcert turret.localhost

      - name: Generate signing certs
        run: |
          openssl ecparam -out certs/signing/ec_key.pem -name prime256v1 -genkey
          openssl req -new -x509 -key certs/signing/ec_key.pem -out certs/signing/ec_cert.pem -days 365 -subj "/O=Turret/OU=Local Development"

      - name: Cache npm dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn

      - name: Configure dotenv
        run: cp .env.dist .env

      - name: Migrate the database
        run: node scripts/syncDatabase.js

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Test End-to-end
        run: yarn test:e2e
